[project]
name = "claw-test-gen"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aerich>=0.8.1",
    "asyncpg>=0.31.0",
    "fastapi-cdn-host>=0.10.0",
    "fastapi[standard]>=0.136.0",
    "gunicorn>=25.3.0",
    "jinja2>=3.1.6",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-deepseek>=1.0.1",
    "langgraph-cli[inmem]>=0.4.23",
    "pyaml-env>=1.2.2",
    "redis>=7.4.0",
    "requests>=2.33.1",
    "tortoise-orm>=1.1.7",
]

[[tool.uv.index]]
url = "http://mirrors.aliyun.com/pypi/simple"
default = true
